"arrowParens" = "always"
"bracketSameLine" = false
"bracketSpacing" = true
"jsxSingleQuote" = false
"printWidth" = 100
"semi" = false
"singleQuote" = true
"trailingComma" = "es5"
"tabWidth" = 4
"useTabs" = false
plugins = ['prettier-plugin-tailwindcss']